name: Deploy to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: capersports-api
  NODE_VERSION: '18.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout code'
      uses: actions/checkout@v3
    
    - name: 'Set up Node.js'
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: server/package-lock.json
    
    - name: 'Install server dependencies'
      run: |
        cd server
        npm ci --production
    
    - name: 'Create deployment package'
      run: |
        cd server
        # Exclude unnecessary files from deployment
        zip -r ../deploy.zip . \
          -x "node_modules/*" \
          -x ".env" \
          -x ".env.*" \
          -x ".git/*" \
          -x "*.log" \
          -x "test/*" \
          -x "*.test.js" \
          -x ".DS_Store"
        cd ..
    
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: deploy.zip
    
    - name: 'Clean up deployment package'
      run: rm -f deploy.zip
    
    - name: 'Wait for deployment to complete'
      run: sleep 30
    
    - name: 'Test deployment health'
      run: |
        echo "Testing health endpoint..."
        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/api/health)
        echo "Health check returned: $RESPONSE"
        if [ "$RESPONSE" != "200" ]; then
          echo "Health check failed with status code: $RESPONSE"
          exit 1
        fi
        echo "✅ Deployment successful and healthy!"
    
    - name: 'Notify on failure'
      if: failure()
      run: |
        echo "❌ Deployment failed!"
        echo "Check the logs above for details."
        echo "Common issues:"
        echo "  1. App Service is stopped - run: az webapp start --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group capersports-rg"
        echo "  2. Missing environment variables in Azure Portal"
        echo "  3. Publish profile expired - regenerate and update GitHub secret"
