name: Deploy to Azure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install server dependencies
      run: |
        cd server
        npm ci --production

<<<<<<< HEAD
    - name: Create deployment package
      run: |
        # Remove unnecessary files to reduce package size
        rm -rf client/node_modules client/build .git
        # Create a clean deployment package
        zip -r deployment.zip . -x "*.git*" "client/node_modules/*" "client/build/*" "node_modules/.cache/*"

    - name: Deploy Backend to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_BACKEND_APP_NAME }}
        publish-profile: ${{ secrets.AZURE_BACKEND_PUBLISH_PROFILE }}
        package: deployment.zip

    # Frontend deployment
    - name: Install frontend dependencies
=======
    - name: Install client dependencies
>>>>>>> parent of 03364ed (commit)
      run: |
        cd client
        npm ci

    - name: Build client application
      run: |
        cd client
        npm run build
      env:
        REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
        REACT_APP_ENV: production
        REACT_APP_STRIPE_PUBLISHABLE_KEY: ${{ secrets.REACT_APP_STRIPE_PUBLISHABLE_KEY }}

    - name: Copy client build to server
      run: |
        mkdir -p server/public
        cp -r client/build/* server/public/

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_APP_NAME }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: ./server

    - name: Deploy to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "/client"
        api_location: ""
        output_location: "build"
