# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - capersports-api

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
      - '.github/workflows/main_capersports-api.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout code'
      uses: actions/checkout@v4
    
    - name: 'Set up Node.js'
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    
    - name: 'Create deployment package'
      run: |
        cd server
        # Package server files for deployment
        zip -r ../deploy.zip . \
          -x "node_modules/*" \
          -x ".env" \
          -x ".env.*" \
          -x ".git/*" \
          -x "*.log" \
          -x "*.zip" \
          -x ".DS_Store"
        cd ..
        echo "Deployment package created:"
        ls -lh deploy.zip
        echo "Checking for important files in server folder:"
        ls -la server/server.js
        ls -la server/routes/clients-azure.js
    
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'capersports-api-bwbecxggbkbnd2ep'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: deploy.zip
    
    - name: 'Clean up'
      run: rm -f deploy.zip
    
    - name: 'Wait for deployment'
      run: sleep 30
    
    - name: 'Test deployment'
      run: |
        echo "Testing health endpoint..."
        curl -s https://capersports-api-bwbecxggbkbnd2ep.centralindia-01.azurewebsites.net/api/health || echo "Health check response received"
        
        echo "Testing clients endpoint..."
        curl -s https://capersports-api-bwbecxggbkbnd2ep.centralindia-01.azurewebsites.net/api/clients || echo "Clients endpoint response received"
        
        echo "✅ Deployment completed!"

